### ISSUE TITLE
MAJOR BREAKING CHANGE in drop of node 6 support

### ISSUE THREAD

**Issue by regevbr** [nstepien/iltorb#102]
Hi,

You have dropped the node 6 support, which is acceptable, but that is a breaking change and you released it as a patch version (2.4.4) thus causing all my projects to break!

Can you please revert the release from npm and release that change under 3.0.0?

Thanks

**Comment by regevbr** [comment]
@MayhemYDG can you please look into it?

**Comment by MayhemYDG** [comment]
- Can you pin iltorb to `2.4.3` in your `package.json` file?
- If iltorb is a sub-dependency, you can try adding iltorb as a direct dependency, set to `2.4.3` so it replaces/dedupes the subdependencies.
- An another alternative would be to install the compilation tools, I think it might still work for node 6.

**Comment by regevbr** [comment]
@MayhemYDG thanks, I already did that, but I'm sure I'm not the only one being affected... I believe the right thing is to fix the issue and release a new major version...

**Comment by MayhemYDG** [comment]
I've added the previous binaries from 2.4.3 for node 6 to the 2.4.4 relelase, let me know if that fixes it for you.

**Comment by XhmikosR** [comment]
@MayhemYDG it seems the problem is still present :/

https://github.com/twbs/bootstrap/pull/29808/checks?check_run_id=338840077#step:15:19

I'd say the best solution would be to release a new patch version with Node.js 6.x support back.

**Comment by MayhemYDG** [comment]
Forgot to rename the filename, so it shouldn't 404 anymore.

**Comment by XhmikosR** [comment]
Confirmed now it works :)
