### ISSUE TITLE
Bug: compiled against a different Node.js version using NODE_MODULE_VERSION 79. This version of Node.js requires NODE_MODULE_VERSION 73

### ISSUE THREAD

**Issue by EvilSpark** [nstepien/iltorb#103]
Resolve error: The module '/home/evilspark/Codes/FicTale/node_modules/iltorb/build/bindings/iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

I suddenly started getting this error. It happened after i removed my nodemodules folder and reinstalled them.

**Comment by nstepien** [comment]
@EvilSpark is this still happening?

**Comment by EvilSpark** [comment]
Nah. It was my mistake. I forgot to close it.
