### ISSUE TITLE
Consider switching to the BrotliCompress available in Node.js API

### ISSUE THREAD

**Issue by ivan-aksamentov** [nstepien/iltorb#92]
Brotli compression algorithm has landed earlier this year into Node.js core and is exposed via `zlib` module since v11.7.0. This version of the compressor requires only Node.js itself and no other external modules or binaries.

Please consider switching to this algorithm on supported configurations, while falling back to binaries only where the new API is not available (on Node < 11.7.0), both during installation (that is, downloading/building binaries conditionally) and on runtime.

Potentially, the usage of the Node.js API can be made optional, via a new config flag, and possibly disabled by default until Node.js 12 enters LTS phase later this year.

I believe this change will alleviate the difficulties some of the users (and users of downstream packages) have with pre-built binaries and node-gyp, will definitely speed up the installation, as well as may give some more confidence regarding security. Personally, I am particularly interested to see the new algorithm to be used in `gulp-brotli` (see issue [#5](https://github.com/MayhemYDG/gulp-brotli/issues/5) there).

See also:
 - [zlib.createBrotliCompress([options])](https://nodejs.org/api/zlib.html#zlib_zlib_createbrotlicompress_options)
 - [Node.js issue #18964](https://github.com/nodejs/node/issues/18964)
 - [Node.js PR #24938](https://github.com/nodejs/node/pull/24938)
 - [`compression-webpack-plugin` already supports brotli via the new API](https://github.com/webpack-contrib/compression-webpack-plugin#using-brotli)

**Comment by nstepien** [comment]
`iltorb` is now a deprecated package, please use the `zlib` module directly.
